routes:
    - route: "^.+\\.(js|css|svg|ttf)$"
      #  cache static assets for 3 months
      headers:
         Cache-Control: "max-age=7884000, no-transform, public"
      gzip: true
    - route: "^.+\\.(png|jpg)$"
      headers:
         Cache-Control: "max-age=7884000, no-transform, public"
      gzip: false
    - route: "^.+\\.(html|xml|json|js)$"
      gzip: true
