defaults: &defaults
  working_directory: /tmp/petersouter.xyz
  environment:
    - SOURCE_DIR: /tmp/petersouter.xyz/public
    - S3_BUCKET: petersouter.xyz
    - S3_REGION: eu-west-1


version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: monachus/hugo:v0.54.0-3
    steps:
      - checkout
      - run:
          name: Compile site
          command: /usr/local/bin/hugo --destination "$SOURCE_DIR"
      - run:
          name: Persist .go3up.json for upload
          command: cp .circleci/.go3up.json /tmp/petersouter.xyz/
      - run:
          name: Persist .go3up.txt for upload
          command: cp .circleci/.go3up.txt /tmp/petersouter.xyz/
      - persist_to_workspace:
          root: /tmp/petersouter.xyz
          paths:
            - public
            - .go3up.json
            - .go3up.txt

  upload-prod:
    <<: *defaults
    docker:
      - image: petems/go3up
    steps:
      - attach_workspace:
          at: /tmp/petersouter.xyz
      - run:
          name: Upload to s3
          command: /usr/local/bin/go3up -source="$SOURCE_DIR" -region="$S3_REGION" -bucket="$S3_BUCKET" --verbose

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build
      - upload-prod:
          requires:
            - build
          filters:
            branches:
              only: master
